#!/bin/bash
#get nasa's astronomy picture of the day

#set the first arguement as the last part of the url before .html
apodSelector=ap
if [ ! -z $1 ]; then
	apodSelector=$1
fi

#get the html file of the apod page
apodPageUrl=https://apod.nasa.gov/apod/${apodSelector}.html
echo "getting ${apodPageUrl}"
apodPageHTML=$(curl -L $apodPageUrl)
echo "got ${apodPageUrl}"

imagePaths=$(echo "$apodPageHTML" | grep -Eo "image/.*\.[^'\"]+" )
#exit if NASA APOD image not found
if [ -z "$imagePaths" ]; then
	echo -e "No images as NASA APOD today \n$(echo "$apodPageHTML" | grep -i .*src.*)"
	exit 0
fi

#get the URLs of the images
apodImgUrls=()
for imagePath in ${imagePaths}; do
	echo $imagePath
	#construct the url
	apodImgUrls+=("https://apod.nasa.gov/apod/${imagePath}")
done
#image saving location
picsDir=$HOME/Pictures/random_wallpapers/nasaApod
picName=$(echo ${apodImgUrls[0]} | awk -F'/' '{print $NF}')
picPath=$picsDir/$picName

#exit with success if the pic is already found
if [ -e $picPath ]; then
	#print in color
	echo -e "nasa apod \e[33m$picName\e[0m found\e"
	exit 0
fi

#get and save the image
for imageUrl in "${apodImgUrls[@]}";do
	curl -LO $imageUrl --output-dir $picsDir
	echo saved $(echo $imageUrl | awk -F'/' '{print $NF}')
done
